# Generated by Django 5.2.7 on 2025-10-17 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estatus",
            field=models.CharField(default="pendiente", max_length=20),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="fecha",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
