# Generated by Django 5.2.7 on 2025-10-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_pedido_estatus_alter_pedido_fecha_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
