# Generated by Django 5.2.7 on 2025-10-17 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_pedido_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
